### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by audvin** [gtap-dev/gravityforms-composer-installer#1]
Seeing that your GitHub org's url has changed I used `"gtap-dev/gravityforms-composer-installer": "dev-master"` instead of `"gotoandplay/gravityforms-composer-installer": "dev-master"`. But install still fails with this message:

` - gravityforms/gravityforms 2.4.6.15 requires gtap-dev/gravityforms-composer-installer dev-master -> no matching package found.`

Changing `minimum-stability` to `dev` yielded same result.

**Comment by ngstigator** [comment]
I'm seeing this even after forking and adding the repository explicitly. Perhaps I'll do a bit of digging but granted I don't have the most experience with composer.

Hoping the maintainer can respond as this is probably something simple that's been overlooked.

**Comment by mihkeleidast** [comment]
Hey, it turns out in order to use a development package as a dependency, it needs to be required standalone first.

So running `composer require gotoandplay/gravityforms-composer-installer:dev-master` before `composer require gravityforms/gravityforms:*` should work, as that's how I myself am using this package now.

I'll try to find some time to publish the package to packagist in the coming weeks so the usage would be simpler.

**Comment by firstchair** [comment]
I added it as a package but getting another error:
Failed to execute unzip -qq  'public/content/plugins/gravityforms//0dce008b6adc98217d6c0b447608e12f.php' -d '/Users/......./Dev/wordpress-setup/public/vendor/composer/6628b8f2'

**Comment by ngstigator** [comment]
@risker Thanks for the tip to require dependencies first! Unfortunately, I'm not able to find a match for neither the newly renamed package...
```
  [InvalidArgumentException]                                                                         
  Could not find a matching version of package gtap-dev/gravityforms-composer-installer. Check the   
  package spelling, your version constraint and that the package is available in a stability which   
  matches your minimum-stability (dev).
 ```
 nor the old one.
```
  [InvalidArgumentException]                                                                         
  Could not find a matching version of package gotoandplay/gravityforms-composer-installer. Check t  
  he package spelling, your version constraint and that the package is available in a stability whi  
  ch matches your minimum-stability (dev).
 ```

**Comment by mihkeleidast** [comment]
I've now published this package to packagist: https://packagist.org/packages/gotoandplay/gravityforms-composer-installer

Defining a repository as follows (also in the readme) should work now without additional steps:
```json
{
  "type": "package",
  "package": {
    "name": "gravityforms/gravityforms",
    "version": "2.4.6.15",
    "type": "wordpress-plugin",
    "dist": {
      "type": "zip",
      "url": "http://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key={%WP_PLUGIN_GF_KEY}"
    },
    "require": {
      "composer/installers": "^1.4",
      "gotoandplay/gravityforms-composer-installer": "^1.0"
    }
  }
},
```

**Comment by ngstigator** [comment]
@risker many thanks! confirming that defining a repo now works as advertised :-)

**Comment by audvin** [comment]
@risker Thanks. I'm still running into two issues:

1. HTTP vs HTTPS

Got this error during install: 

```
 - Installing gravityforms/gravityforms (2.4.6.15): 


Installation failed, reverting ./composer.json to its original content.

                                                                                                                                                                                                                                             
  [Composer\Downloader\TransportException]                                                                                                                                                                                                   
  Your configuration does not allow connections to http://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key=XXXX. See https://getcomposer.org/doc/06-config.md#  
  secure-http for details.                                                                                                                                                                                                                   
                                                                                                  
```

Changing dist url to `"url": "https://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key={%WP_PLUGIN_GF_KEY}"` fixed that.


2. Issues with unzipping


```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing gravityforms/gravityforms (2.4.6.15): Downloading (100%)         
    Failed to execute unzip -qq  'wp-content/plugins/gravityforms//92d9480accb0b282535009f1aee6a19a.php' -d '/Users/audun/git/hhp/vendor/composer/2fc38c89'

[wp-content/plugins/gravityforms//92d9480accb0b282535009f1aee6a19a.php]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of wp-content/plugins/gravityforms//92d9480accb0b282535009f1aee6a19a.php or
        wp-content/plugins/gravityforms//92d9480accb0b282535009f1aee6a19a.php.zip, and cannot find wp-content/plugins/gravityforms//92d9480accb0b282535009f1aee6a19a.php.ZIP, period.

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

    Invalid zip file, retrying...

```

I'm seeing a double slash there `//` in the path...

**Comment by nicholasscottfish** [comment]
For anyone who is still coming across errors with the Gravity Forms installer:

```bash
 End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of wp-content/plugins/gravityforms//eb8aedef4b1944061e22c0364d8a59bc.php or
        wp-content/plugins/gravityforms//eb8aedef4b1944061e22c0364d8a59bc.php.zip, and cannot find wp-content/plugins/gravityforms//eb8aedef4b1944061e22c0364d8a59bc.php.ZIP, period.

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

    Invalid zip file, retrying...

```

The fix for us wass to remove the gotoandplay package from the vendor directory and re-run composer update. It then re-installed the installer and successfully installs the zip file.

We are not sure why this resolves the issue but it seems to work every time.

**Comment by prikkprikkprikk** [comment]
> The fix for us wass to remove the gotoandplay package from the vendor directory and re-run composer update. It then re-installed the installer and successfully installs the zip file.

Thank you! This solved it for me.
