### ISSUE TITLE
Get specific version

### ISSUE THREAD

**Issue by ouun** [gtap-dev/gravityforms-composer-installer#12]
Hi there,

thanks for the useful plugin. I need an older version as there is a bug I am waiting to get fixed. 
However I wonder if there is a possibillity to set the version in the download url as parameter. Tried it with `&version=2.4.21.6` & `&=2.4.21.6`. But it always loads the latest package.

Kind regards,

Philipp

**Comment by ouun** [comment]
Wanted to add a PR but finally found out that Gravity Forms does not give access to older versions. That's a joke, isn't it?

**Comment by mihkeleidast** [comment]
Yeah :(

We ourselves are planning to setup a [SatisPress](https://github.com/cedaro/satispress) instance that would remove the need for these "private installer plugins" and allow usage of older versions.
