### ISSUE TITLE
Take note of the option name

### ISSUE THREAD

**Issue by szepeviktor** [gtap-dev/gravityforms-composer-installer#8]
Please add to the README that the license key may be found in the `rg_gforms_key` option.
Thank you.

**Comment by mihkeleidast** [comment]
Not sure what you mean by this, but you should get your license key from the Gravity Forms website, not from a database. The value needs to get to the database from somewhere :)

**Comment by szepeviktor** [comment]
@mihkeleidast I had a complete-wp-install.ZIP and a database.SQL dump to begin with.
Maybe others are in my shoe.
